name: tradr-summerschool
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - pip:
        - tensorflow==1.1
        - keras==1.2
